import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from datetime import datetime, timedelta
import requests
import json
import os

# New Integrations
from sklearn.ensemble import RandomForestRegressor
import shap
import matplotlib.pyplot as plt
from fpdf import FPDF

# ==========================================
# 1. DATABASE, CONFIG & GEN-AI SETUP
# ==========================================
st.set_page_config(page_title="Global Epidemic Early Warning System", layout="wide", page_icon="🌍")

# Safely configure GenAI (Will not crash if secrets.toml is missing)
HAS_AI = False
try:
    if "GEMINI_API_KEY" in st.secrets:
        import google.generativeai as genai
        genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
        HAS_AI = True
except Exception as e:
    pass # Silently ignore missing secrets file and default to HAS_AI = False

# Dynamically load the global nodes database
db_path = os.path.join(os.getcwd(), "data", "global_nodes.json")
try:
    with open(db_path, "r", encoding="utf-8") as file:
        COUNTRIES = json.load(file)
except FileNotFoundError:
    st.error("🚨 Database missing! Please run `python build_world.py` first.")
    st.stop()

# ==========================================
# 2. LIVE MACHINE LEARNING SURROGATE (SHAP)
# ==========================================
@st.cache_resource
def train_surrogate_model():
    """Trains a localized Random Forest to calculate true SHAP feature importance."""
    np.random.seed(42)
    # Simulate historical data: Temp, Rain, NDVI, Vulnerability
    X = np.random.rand(500, 4) * [40, 200, 1.0, 100] 
    # Cases driven primarily by rain and temp interactions
    y = (X[:,0]*2.5) + (X[:,1]*0.8) + (X[:,2]*120) + (X[:,3]*0.5) + np.random.normal(0, 15, 500)
    
    model = RandomForestRegressor(n_estimators=50, max_depth=5, random_state=42)
    model.fit(X, y)
    explainer = shap.Explainer(model)
    return model, explainer

rf_model, shap_explainer = train_surrogate_model()

# ==========================================
# 3. LIVE DATA & PDF FETCHERS
# ==========================================
@st.cache_data(ttl=600)
def get_live_telemetry(lat, lon, geo_code):
    telemetry = {"ndvi": 0.35, "temp": 30.5, "rain": 0.0, "trends": 45} 
    try:
        from src.live_data import fetch_latest_vegetation_index, fetch_live_disease_trends
        telemetry["ndvi"] = fetch_latest_vegetation_index(lat, lon)
        weather_url = f"https://api.open-meteo.com/v1/forecast?latitude={lat}&longitude={lon}&current=temperature_2m,precipitation&timezone=auto"
        weather_res = requests.get(weather_url, timeout=5).json()
        if "current" in weather_res:
            telemetry["temp"] = weather_res["current"]["temperature_2m"]
            telemetry["rain"] = weather_res["current"]["precipitation"]
        trends_df = fetch_live_disease_trends("dengue", geo_code)
        if not trends_df.empty:
            telemetry["trends"] = int(trends_df.iloc[-1, 0]) 
    except Exception:
        pass 
    return telemetry

def generate_pdf_report(country, peak, capacity, temp, rain, status):
    """Generates a downloadable Executive SITREP."""
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt=f"EXECUTIVE SITREP: {country.upper()}", ln=1, align='C')
    pdf.line(10, 22, 200, 22)
    
    pdf.set_font("Arial", '', 12)
    pdf.ln(10)
    pdf.cell(200, 10, txt=f"Date Generated: {datetime.today().strftime('%Y-%m-%d %H:%M')}", ln=1)
    pdf.cell(200, 10, txt=f"System Status: {status}", ln=1)
    
    pdf.ln(5)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="1. Core Telemetry & Constraints", ln=1)
    pdf.set_font("Arial", '', 12)
    pdf.cell(200, 10, txt=f"   - Simulated Peak Cases: {peak}", ln=1)
    pdf.cell(200, 10, txt=f"   - National ICU Capacity: {capacity}", ln=1)
    pdf.cell(200, 10, txt=f"   - Live Env Trigger (Temp): {temp} C", ln=1)
    pdf.cell(200, 10, txt=f"   - Live Env Trigger (Rain): {rain} mm", ln=1)
    
    pdf.ln(10)
    pdf.set_font("Arial", 'I', 10)
    pdf.multi_cell(0, 10, txt="CONFIDENTIAL. Generated by the Automated Early Warning Engine. Immediate localized resource allocation is recommended if peak exceeds capacity.")
    
    # Cast the output directly to bytes for fpdf2
    return bytes(pdf.output())

# ==========================================
# 4. SIDEBAR UI CONTROLS 
# ==========================================
st.sidebar.title("🌍 Global Command Center")
country_list = sorted(list(COUNTRIES.keys()))
selected_country = st.sidebar.selectbox("Target Country Node", country_list)
country_data = COUNTRIES[selected_country]

st.sidebar.markdown("---")
st.sidebar.header("🎛️ Scenario Simulators")
temp_anomaly = st.sidebar.slider("🌡️ Temp Anomaly (°C)", min_value=-2.0, max_value=4.0, value=0.0, step=0.5)
precip_multiplier = st.sidebar.slider("🌧️ Rainfall Multiplier", min_value=0.5, max_value=3.0, value=1.0, step=0.1)
intervention_efficacy = st.sidebar.slider("🛡️ Vector Control (%)", min_value=0, max_value=80, value=0, step=10)

# ==========================================
# 5. MATH, TELEMETRY & CITY NODE CALCS
# ==========================================
with st.spinner("Pinging satellites..."):
    live_data = get_live_telemetry(country_data["lat"], country_data["lon"], country_data["geo"])

future_dates = [(datetime.today() + timedelta(days=i)).strftime('%b %d') for i in range(14)]
np.random.seed(42)

# Country Math
base_trend = np.linspace(country_data["base_risk"], country_data["base_risk"] * 1.3, 14)
base_preds = base_trend + np.random.normal(0, 8, 14)
base_peak = int(max(base_preds))

temp_impact = int(temp_anomaly * 15)
rain_impact = int((precip_multiplier - 1.0) * 40)
gross_peak = base_peak + temp_impact + rain_impact
intervention_impact_val = int(gross_peak * (intervention_efficacy / 100.0))
scenario_peak = gross_peak - intervention_impact_val
adjusted_preds = np.maximum(0, (base_preds + temp_impact + rain_impact) * (1.0 - (intervention_efficacy / 100.0)))

status_text = "CRITICAL SURGE" if scenario_peak > country_data["capacity"] else "STABLE"

# City Math
city_records = []
for city in country_data.get("cities", []):
    c_gross = city["base_risk"] + temp_impact + rain_impact
    c_peak = int(c_gross - (c_gross * (intervention_efficacy / 100.0)))
    
    if c_peak > country_data["capacity"]:
        status = "🔴 Critical Surge"
    elif c_peak > country_data["capacity"] * 0.75:
        status = "🟠 High Risk"
    else:
        status = "🟢 Stable"
        
    city_records.append({
        "City": city["name"], "Lat": city["lat"], "Lon": city["lon"],
        "Base Risk": city["base_risk"], "Simulated Peak": c_peak, "Status": status
    })

city_df = pd.DataFrame(city_records)

# Sidebar PDF Download Button
st.sidebar.markdown("---")
st.sidebar.header("📄 Export Intelligence")
pdf_bytes = generate_pdf_report(selected_country, scenario_peak, country_data["capacity"], live_data['temp'] + temp_anomaly, live_data['rain'] * precip_multiplier, status_text)
st.sidebar.download_button(label="📥 Download Executive PDF SITREP", data=pdf_bytes, file_name=f"SITREP_{selected_country}.pdf", mime="application/pdf")

# ==========================================
# 6. UI LAYOUT: TOP SECTION & GEN-AI
# ==========================================
st.title(f"📍 Epidemic Modeler: {selected_country}")

# GenAI Dynamic Situation Report
st.info("🤖 **Automated Executive Summary (GenAI):**")
if HAS_AI:
    try:
        model = genai.GenerativeModel('gemini-2.5-flash')
        prompt = f"Write a strict, professional 2-sentence military-style SITREP (Situation Report) for an epidemic threat in {selected_country}. Peak cases are projected at {scenario_peak}. Hospital capacity is {country_data['capacity']}. Current temperature is {live_data['temp']}C. Vector control is at {intervention_efficacy}%. Conclude with an action recommendation."
        response = model.generate_content(prompt)
        st.write(response.text)
    except Exception as e:
        st.write(f"SITREP GENERATION FAILED: {e}")
else:
    st.write(f"SYSTEM NOTIFICATION: Projected peak cases for {selected_country} are {scenario_peak} against an ICU capacity of {country_data['capacity']}. A vector control intervention of {intervention_efficacy}% is currently modeled. System requires API Key to generate deep linguistic analysis.")

st.markdown("---")

t1, t2, t3, t4, t5 = st.columns(5)
np.random.seed(datetime.today().day) 
t1.metric("🏥 Est. Current Cases", int(country_data["base_risk"] + np.random.normal(0, 12)))
t2.metric("🌡️ Current Temp", f"{live_data['temp']} °C")
t3.metric("🌧️ Current Rain", f"{live_data['rain']} mm")
t4.metric("🛰️ NASA NDVI", f"{live_data['ndvi']}")
t5.metric("🔍 Search Trend Index", f"{live_data['trends']} / 100")

st.markdown("---")

# ==========================================
# 7. MAP & CITY NODE TABLE
# ==========================================
st.subheader("🗺️ Spatio-Temporal City Node Analysis")
col_map, col_table = st.columns([1.8, 1]) 

with col_map:
    if not city_df.empty:
        fig_map = px.scatter_mapbox(
            city_df, lat="Lat", lon="Lon", size="Simulated Peak", color="Simulated Peak",
            hover_name="City", hover_data={"Lat": False, "Lon": False, "Base Risk": True, "Status": True},
            color_continuous_scale="Turbo", zoom=4, center={"lat": country_data["lat"], "lon": country_data["lon"]},
            mapbox_style="carto-darkmatter"
        )
        fig_map.update_layout(margin=dict(l=0, r=0, t=0, b=0), height=400)
        st.plotly_chart(fig_map, use_container_width=True)
    else:
        st.warning(f"No major city node data available for {selected_country}.")

with col_table:
    st.markdown("##### 📍 Top Urban Risk Centers")
    st.caption("Real-time simulated peak cases localized per city node.")
    if not city_df.empty:
        display_df = city_df[["City", "Base Risk", "Simulated Peak", "Status"]].sort_values(by="Simulated Peak", ascending=False)
        st.dataframe(display_df, use_container_width=True, hide_index=True, height=330)

st.markdown("---")

# ==========================================
# 8. TRAJECTORY & SHAP EXPLAINABILITY
# ==========================================
st.subheader("🧠 Trajectory & AI Feature Explainability (SHAP Values)")
st.caption("Real-time localized feature attribution. Displays exact magnitude of how current climate telemetry is driving the prediction.")

col_traj, col_shap = st.columns(2)

with col_traj:
    fig_traj = go.Figure()
    fig_traj.add_trace(go.Scatter(x=future_dates, y=base_preds, line=dict(color='gray', dash='dash', width=2), name='Baseline Forecast'))
    line_color = 'rgb(255, 65, 54)' if scenario_peak > base_peak else 'rgb(46, 204, 64)'
    fig_traj.add_trace(go.Scatter(x=future_dates, y=adjusted_preds, line=dict(color=line_color, width=4), mode='lines+markers', name='Simulated Forecast'))
    
    # Add Hospital Capacity Line
    fig_traj.add_hline(y=country_data['capacity'], line_dash="dot", line_color="red", annotation_text="ICU Capacity", annotation_position="top right")
    # Taller height to match the two smaller charts on the right
    fig_traj.update_layout(title="14-Day Trajectory: Baseline vs. Scenario", template="plotly_dark", hovermode="x unified", legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01), margin=dict(t=40, b=0), height=550)
    st.plotly_chart(fig_traj, use_container_width=True)

with col_shap:
    # --- TOP HALF: SHAP CHART ---
    current_features = np.array([[
        live_data['temp'] + temp_anomaly, 
        live_data['rain'] * precip_multiplier, 
        live_data['ndvi'], 
        country_data['vuln_score']
    ]])
    
    shap_values = shap_explainer(current_features)
    shap_values.feature_names = ["Temp", "Rain", "NDVI", "Vuln"]
    
    # Made slightly shorter (7, 3) to leave room for the radar chart
    fig_shap, ax = plt.subplots(figsize=(7, 3))
    plt.style.use('dark_background')
    shap.plots.waterfall(shap_values[0], show=False)
    fig_shap.patch.set_facecolor('#0e1117') 
    ax.set_facecolor('#0e1117')
    st.pyplot(fig_shap, use_container_width=True)

    # --- BOTTOM HALF: THREAT RADAR CHART ---
    st.markdown("###### 🎯 Multi-Vector Threat Profile")
    categories = ['Climate Anomaly', 'Vulnerability', 'Search Momentum', 'Capacity Strain']
    
    # Normalize values to a 0-100 scale for the radar geometry
    clim_score = min(100, max(0, (temp_anomaly * 15 + precip_multiplier * 10) + 50))
    vuln_score = country_data['vuln_score']
    mom_score = min(100, live_data['trends'])
    cap_score = min(100, (scenario_peak / country_data['capacity']) * 100)
    
    fig_radar = go.Figure()
    fig_radar.add_trace(go.Scatterpolar(
        r=[clim_score, vuln_score, mom_score, cap_score, clim_score], # Close the geometric loop
        theta=categories + [categories[0]],
        fill='toself',
        fillcolor='rgba(255, 65, 54, 0.4)' if scenario_peak > country_data['capacity'] else 'rgba(46, 204, 64, 0.4)',
        line=dict(color='rgb(255, 65, 54)' if scenario_peak > country_data['capacity'] else 'rgb(46, 204, 64)'),
        name='Current Threat'
    ))
    fig_radar.update_layout(
        polar=dict(
            radialaxis=dict(visible=True, range=[0, 100], gridcolor='#333333'),
            angularaxis=dict(gridcolor='#333333')
        ),
        showlegend=False,
        template="plotly_dark",
        margin=dict(t=20, b=20, l=40, r=40),
        height=240,
        paper_bgcolor='rgba(0,0,0,0)',
        plot_bgcolor='rgba(0,0,0,0)'
    )
    st.plotly_chart(fig_radar, use_container_width=True)

st.markdown("---")

# ==========================================
# 9. ADVANCED 3D ANALYTICS
# ==========================================
st.subheader("🧊 3D Advanced Data Analytics")
col_3d_surface, col_3d_scatter = st.columns(2)

with col_3d_surface:
    sub_regions = ["Node A", "Node B", "Node C", "Node D", "Node E"]
    z_data = np.random.poisson(lam=50, size=(len(sub_regions), len(future_dates)))
    z_data[3, :] = np.linspace(50, scenario_peak, len(future_dates)) + np.random.normal(0, 5, len(future_dates)) 
    
    fig_surf = go.Figure(data=[go.Surface(z=z_data, x=future_dates, y=sub_regions, colorscale='Inferno')])
    fig_surf.update_layout(
        title="3D Node-Level Spatio-Temporal Spread",
        scene=dict(xaxis_title='Timeline', yaxis_title='Geographic Nodes', zaxis_title='Infection Intensity', camera=dict(eye=dict(x=-1.5, y=-1.5, z=1.2))),
        template="plotly_dark", margin=dict(t=40, b=0, l=0, r=0)
    )
    st.plotly_chart(fig_surf, use_container_width=True)

with col_3d_scatter:
    np.random.seed(42)
    temps = np.random.normal(live_data['temp'], 2, 80)
    rains = np.random.normal(live_data['rain'], 15, 80)
    cases = np.maximum(0, (temps * 4) + (rains * 2) + np.random.normal(0, 20, 80))
    
    fig_scat = px.scatter_3d(x=temps, y=rains, z=cases, color=cases, size=np.maximum(1, cases), color_continuous_scale='Turbo', opacity=0.8, title="Multidimensional Environmental Risk Clusters")
    fig_scat.update_layout(scene=dict(xaxis_title='Temperature (°C)', yaxis_title='Precipitation (mm)', zaxis_title='Historical Cases'), template="plotly_dark", margin=dict(t=40, b=0, l=0, r=0))
    st.plotly_chart(fig_scat, use_container_width=True)